# Generated by Django 4.2.21 on 2025-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('game_duration', models.DurationField()),
                ('food_eaten', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='madlibs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paragraph', models.TextField()),
                ('noun', models.IntegerField(default=0)),
                ('adjective', models.IntegerField(default=0)),
                ('verb', models.IntegerField(default=0)),
                ('funny_word', models.IntegerField(default=0)),
                ('funny_name', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='madlibs_user_history',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('paragraph_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('noun', models.JSONField(default=list, verbose_name=models.CharField(max_length=200))),
                ('adjective', models.JSONField(default=list, verbose_name=models.CharField(max_length=200))),
                ('verb', models.JSONField(default=list, verbose_name=models.CharField(max_length=200))),
                ('funny_word', models.JSONField(default=list, verbose_name=models.CharField(max_length=200))),
                ('funny_name', models.JSONField(default=list, verbose_name=models.CharField(max_length=200))),
            ],
        ),
    ]
