# Generated by Django 4.2.21 on 2025-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlibs',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='madlibs_user_history',
            name='number',
            field=models.JSONField(default=list, verbose_name=models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='madlibs',
            name='job',
            field=models.IntegerField(default=0),
        ),
    ]
