# Generated by Django 4.2.21 on 2025-06-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madlibs_user_history',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='madlibs_user_history',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='madlibs_user_history',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
