# Generated by Django 4.2.21 on 2025-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0002_madlibs_number_madlibs_user_history_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='flappy_bird',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
