# Generated by Django 4.2.21 on 2025-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0003_flappy_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='flappy_bird',
            name='gap',
            field=models.IntegerField(default=150),
        ),
    ]
