# Generated by Django 4.2.21 on 2025-07-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0004_flappy_bird_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flappy_bird',
            name='gap',
        ),
    ]
