# Generated by Django 4.2.21 on 2025-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0006_hangman_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_image', models.URLField(max_length=2000)),
                ('game_name', models.CharField(max_length=255)),
                ('game_link', models.URLField(max_length=2000)),
            ],
        ),
    ]
