# Generated by Django 4.2.21 on 2025-11-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitai', '0007_game_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='aramaic_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aramaic_word', models.CharField(max_length=255)),
                ('hebrew_translation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='hebrew_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hebrew_word', models.CharField(max_length=255)),
            ],
        ),
    ]
