# Generated by Django 4.2.21 on 2025-06-11 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="A descriptive name for the account (e.g., 'Allowance', 'Savings Account').", max_length=255)),
                ('balance_current', models.DecimalField(decimal_places=2, default=0.0, help_text='The current balance of the account.', max_digits=19)),
                ('currency', models.CharField(default='USD', help_text="The ISO 4217 currency code for this account (e.g., 'USD', 'EUR').", max_length=3)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['member__name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the transaction category (e.g., 'Food', 'Allowance').", max_length=255, unique=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this category is for income or expense.', max_length=7)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="The amount of the transaction. Positive for income, negative for expense (though 'type' is also used).", max_digits=19)),
                ('description', models.CharField(blank=True, help_text="A brief description of the transaction (e.g., 'Bought a toy', 'Weekly allowance').", max_length=255, null=True)),
                ('date', models.DateField(help_text='The date the transaction occurred.')),
                ('type', models.CharField(choices=[('credit', 'Credit (Income)'), ('debit', 'Debit (Expense)')], help_text='Whether this transaction is a credit (adds money) or debit (removes money).', max_length=6)),
                ('account', models.ForeignKey(help_text='The account involved in this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_tracker.account')),
                ('category', models.ForeignKey(blank=True, help_text='The category of this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance_tracker.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the family member.', max_length=255)),
                ('user', models.OneToOneField(help_text='Links to the Django User account for this family member.', on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='member',
            field=models.ForeignKey(help_text='The family member who owns this account.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance_tracker.familymember'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_monthly', models.DecimalField(decimal_places=2, help_text='The maximum amount budgeted for this category per month.', max_digits=19)),
                ('start_date', models.DateField(help_text='The start date from which this budget is active.')),
                ('end_date', models.DateField(blank=True, help_text='The end date until which this budget is active (optional, for recurring budgets).', null=True)),
                ('category', models.ForeignKey(help_text='The category for which this budget is set.', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_tracker.transactioncategory')),
                ('member', models.ForeignKey(help_text='The family member who set this budget.', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_tracker.familymember')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['member__name', 'start_date', 'category__name'],
                'unique_together': {('member', 'category', 'start_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('member', 'account_name')},
        ),
    ]
