from django.urls import path
from .views import api_home, snake, render_add_games, get_game_info, create_game, save_score, create_hangman_word, get_hangman_word, get_hangman_words, delete_flappy_bird_score, rander_hangman, get_flappy_bird_score, get_flappy_bird_top_score, save_flappy_bird_score, tic_tac_toe, render_flappy_bird, main_games_center, two_player, countdown, adding_data, rectangle, calculator, create_data, get_all_templates, like_template, dislike_template, madlibs_game, get_finished_template_by_id, get_finished_data, create_finished_data, get_random_template, delete_data, update_data


urlpatterns = [
    path('', api_home),
    path('snake', snake, name='snake'),
    path('save_score', save_score, name='save_score_api'),
    path('madlibs_game', madlibs_game, name='madlibs_game'),
    path('hangman', rander_hangman, name='hangman'),
    path('get_game_info', get_game_info, name='get_game_info'),
    path('create_game', create_game, name='create_game'),
    path('create_hangman_word', create_hangman_word, name='create_hangman_word'),
    path('get_hangman_word', get_hangman_word, name='get_hangman_word'),
    path('get_hangman_words', get_hangman_words, name='get_hangman_words'),
    path('add_games', render_add_games, name='add_games'),
    path('adding_data', adding_data, name='adding_data'),
    path('create_data', create_data, name='create_data'),
    path('delete_flappy_bird_score/<int:id>', delete_flappy_bird_score, name='delete_flappy_bird_score'),
    path('save_flappy_bird_score', save_flappy_bird_score, name='save_flappy_bird_score'),
    path('get_flappy_bird_score', get_flappy_bird_score, name='get_flappy_bird_score'),
    path('get_flappy_bird_top_score', get_flappy_bird_top_score, name='get_flappy_bird_top_score'),
    path('get_all_templates', get_all_templates, name='get_all_templates'),
    path('get_finished_data', get_finished_data, name='get_finished_data'),
    path('create_finished_data', create_finished_data, name='create_finished_data'),
    path('get_random_template', get_random_template, name='get_random_template'),
    path('get_finished_template_by_id/<int:id>', get_finished_template_by_id, name='get_finished_template_by_id'),
    path('delete_data/<int:id>', delete_data, name='delete_data'),
    path('update_data/<int:id>', update_data, name='update_data'),
    path('like_template/<int:id>', like_template, name='like_template'),
    path('dislike_template/<int:id>', dislike_template, name='dislike_template'),
    path('two_player', two_player, name='two_player'),
    path('calculator', calculator, name='calculator'),
    path('countdown', countdown, name='countdown'),
    path('rectangle', rectangle, name='rectangle'),
    path('main_games_center', main_games_center, name='main_games_center'),
    path('tic_tac_toe', tic_tac_toe, name='tic_tac_toe'),
    path('flappy_bird', render_flappy_bird, name='flappy_bird'),

]